apiVersion: v1
kind: Service
metadata:
  name: zxbk-redis-service
  namespace: qiqi-china-zxbk-prod
  labels:
    service: redis-cluster
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: redis
  selector:
    name: redis-node

---
#redis-write-service
apiVersion: v1
kind: Service
metadata:
  name: zxbk-redis-public-write
  namespace: qiqi-china-zxbk-prod
  labels:
    service: redis-write
spec:
  ports:
    - port: 6379
      name: redis
      nodePort: 45730
  type: NodePort
  selector:
    name: redis-node
    role: master
---
#redis-read-service
apiVersion: v1
kind: Service
metadata:
  name: zxbk-redis-public-read
  namespace: qiqi-china-zxbk-prod
  labels:
    service: redis-read
spec:
  ports:
    - port: 6379
      name: redis
      nodePort: 39557
  type: NodePort
  selector:
    name: redis-node